version: '3.9'

services:
  oidc_provider:
    image: authelia/authelia:latest
    environment:
      TZ: Europe/Warsaw
    volumes:
    - ./docker/oidc_provider:/config:rw
    ports:
    - '0.0.0.0:9091:9091/tcp'
  smtp_trap:
    image: mailhog/mailhog:latest
    ports:
    - '0.0.0.0:1025:1025/tcp'
    - '0.0.0.0:8025:8025/tcp'
  redis:
    image: redis:7.0-alpine
    command: ['redis-server', '--requirepass "secret"']
    ports:
    - '0.0.0.0:6379:6379/tcp'
  redis_commander:
    image: ghcr.io/joeferner/redis-commander
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: default
      REDIS_PASSWORD: secret
    ports:
    - '0.0.0.0:7501:8081/tcp'
  database:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: secret
      TZ: Europe/Warsaw
    volumes:
    - ./docker/database:/docker-entrypoint-initdb.d:ro
    - database_data:/var/lib/mysql:rw
    ports:
    - '127.0.0.1:3306:3306/tcp'
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
    - '0.0.0.0:7500:80/tcp'

volumes:
  database_data: ~
