version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./.docker/keycloak:/opt/keycloak/data/import:ro
    ports:
      - '0.0.0.0:8080:8080/tcp'
