version: '3.9'

services:
  database:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: secret
      TZ: Europe/Warsaw
    volumes:
    - ./docker/database:/docker-entrypoint-initdb.d:ro
    - database_data:/var/lib/mysql:rw
    ports:
    - '127.0.0.1:3306:3306/tcp'
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
    - '0.0.0.0:7500:80/tcp'

volumes:
  database_data: ~
