theme: auto
jwt_secret: 5icYwdp7cbu7mAwZDwvouC8K3x095KEkh6JiUsiXWOeNdqU5PPRDiS7j1ClMzKnK
default_redirection_url: http://localhost:3000/
default_2fa_method: ''

server:
  host: 0.0.0.0
  port: 9091
  path: ''
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ''
    certificate: ''
    client_certificates: [ ]
  headers:
    csp_template: ''

log:
  level: debug

telemetry:
  metrics:
    enabled: false
    address: tcp://0.0.0.0:9959

totp:
  disable: true

webauthn:
  disable: true

duo_api:
  disable: true

ntp:
  address: 'time.cloudflare.com:123'
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false
    custom_url: ''
  refresh_interval: 5m
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      parallelism: 4
      memory: 64

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

access_control:
  default_policy: deny
  networks:
  - name: internal
    networks:
    - 10.10.0.0/16
    - 192.168.2.0/24
  - name: VPN
    networks: 10.9.0.0/16
  rules:
  - domain: 'public.example.com'
    policy: bypass
  - domain: 'singlefactor.example.com'
    policy: one_factor

session:
  name: authelia_session
  domain: localhost
  same_site: none
  secret: BJ7CKFk4INytmSfkHtePAsnkxYCXV6qKcaaHEo9CJdleHxL60UsOxfoBN4vOmfEW
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: GRm9wkRwXR4rAcR7gXvH6bkbkR9Xi4vwoCyYvErJoXTK0peF7mJH7OQ2hnGWgOYQ
  mysql:
    host: database
    port: 3306
    database: oidc_provider
    username: root
    password: secret
    timeout: 5s

notifier:
  disable_startup_check: true
  smtp:
    host: smtp_trap
    port: 1025
    timeout: 5s
    username: ~
    password: ~
    sender: 'OIDC Provider <no-reply@app.com>'
    identifier: localhost
    subject: '{title}'
    startup_check_address: no-reply@app.com
    disable_require_tls: true
    disable_html_emails: false
    tls:
      skip_verify: true
      minimum_version: TLS1.2

identity_providers:
  oidc:
    hmac_secret: 9qYBdyvB6b0OMuheM9TBcafL9mXoPbgDMtmpcnnLtiSQyrPegZjvSK9nCQcReHJC
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAtgqiA4FHrw1CcmY0BtP/dmP9ozxef2zNUps8g97vEw1RZJT5
      2a9rXIWCIAWUqkZLFe7WBRYoj3xN8Q0G5qnf+ebXisLqkEII4hazyCDKnNSwwS7d
      7+mkeVF70sanrkhgGcRRY5e6L2Fyq2bHTOKgYF2pDS+bhL/QkApj7iYeY8bbdfdH
      f4yPDrnZ3giB7J5s7K/oHHfaflaUG27qb4qbxXsduW35g/uJWqXtRkCKBz293+jz
      DxDfk+r6U8p9wRMf08zMBSuhDhvtUrGvuQy/alc+y8rZ21IVEcV2d0pUy6k7ntG7
      xtD3yv9VPBOf3s95h3v1vmvv0N+XSgpf1B+tjwIDAQABAoIBABTpyc0PSBXzNwP/
      e9ChAEMwn43mPJD1Be2Mifo4XUzaBdTBTKbWgUYCzH0zRu3831los8unzQcW57le
      nsFXGLUT8QUu+VWTUIPwybyfD8fOo3O+F58dP1j0pH4FdnQOOoQbSqJfZvNUhaDt
      UM4jZvtLJ0Wth3dLtgEmQG62kF0z4/5BrrGzJGEBhn6hJxgXjMlb3gaIcFhejznC
      hUKOHJZtIuo8ZRq96ZQI6i5xSL7Gk6cuXdJ+LXhhh439HE7Lx2nUBV8CR7E11gG+
      MLXlz114wMzNmjN7r+W2G16W8R72LMbZSDqVU7bzCpb/gGz6oEx5P32jhnx5Tx/P
      MmjSA3ECgYEA/QNeTY4fT8NunSTHP/kJN8LMiJOEc7hQYp9/8u1IZkCLvnk6m77V
      ky/BZBNPbgPFlfIvmTfMHLMLcVXQNETKqgOpzHiSA62SMJMulLoqq6AEMyYQFMNp
      xZ0gXSVIChh0HzzKuGR1KdOO5ekZYKxty5b5jirIBPsMGwSUMNux0TcCgYEAuDDH
      70DlCHpjxP9yXZ7ldMjBssIGLLRyzxsa1Bw9i8OCAq9gTh/mD6u1gQbB8UVsCWc2
      Rg581OFiGr2OOBRnh+GiBbyN9lfiM+epYEnW6m86uZT8qlS9l1JwW/lsa+OdtaDl
      E6RE8fcSzzVBvQV2nXqsotiHC6WnBlCadL3dEmkCgYEAo5vpAEe2EbMztSRSQBj/
      D/LEplCWJup5+LxhVaqA1bZJZ1snPg1SOIJ6EQe3plGEFGluxCpjr+9Lp/cw0ovl
      bbk+tL0G1qAH16dlSMF11FN+Q8EKRxLyM9peUj1Ib1bOyGBcSo6TgP+P+TYZtfzq
      Zuty5q7ddvMMKfB1D38RZlMCgYBi0zGC6kO4r8o2GYToPGgKp+hdnAKqG8t52aYk
      Zl6TTbvE6wn2AOF0SQHij5ihdkkIJouVPRK3OZJknI3hAvmli2deQpO8t9yTUtmq
      4xNfx3wvtIN4dG0g8sd8YbBNltu4ZvJh/oJLfPBnosB5xaOlzPsxiJG0qxWZqsek
      mXYy+QKBgF4uN0TA9hz4bPSLuXwjRisvxxd/zImP9zSJanXA35DI8WPSnw9/DEpl
      VuNPr28pxFSDSIGnO92dCwylg2v7d4unaxjKF37oniMXFLvNlxMtV++nWGwkgXcU
      fqfb3KkO3ODRxedpITOrwBe95xZwKCls7ABLiGg9CeeGL3rJSO/x
      -----END RSA PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
      - authorization
      - token
      - revocation
      - introspection
      allowed_origins:
      - http://localhost:8000
      allowed_origins_from_client_redirect_uris: true
    clients:
    - id: 8d5ac03e-c9a7-48f3-b03b-2890c64811f1
      description: example app
      secret: i8saBrz5xx5QCuPADUpDJ165CPfAPZTxWtjOBjNDDu
      sector_identifier: ''
      public: false
      authorization_policy: one_factor
      pre_configured_consent_duration: ''
      audience: [ ]
      scopes:
      - openid
      - offline_access
      - groups
      - email
      - profile
      redirect_uris:
      - http://localhost:8000/_auth/callback
      grant_types:
      - refresh_token
      - authorization_code
      response_types:
      - code
      response_modes:
      - form_post
      - query
      - fragment
      userinfo_signing_algorithm: none
